# integration tests for nuxt ecosystem projects - scheduled or manual run for all suites
name: nuxt-ecosystem-ci

env:
  # 7 GiB by default on GitHub, setting to 6 GiB
  # https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources
  NODE_OPTIONS: --max-old-space-size=6144
  # configure corepack to be strict but not download newer versions or change anything
  COREPACK_DEFAULT_TO_LATEST: 0
  COREPACK_ENABLE_AUTO_PIN: 0
  COREPACK_ENABLE_STRICT: 1

on:
  schedule:
    - cron: '0 5 * * 1,3,5' # monday,wednesday,friday 5AM
  workflow_dispatch:
    inputs:
      refType:
        description: type of ref
        required: true
        type: choice
        options:
          - branch
          - tag
          - commit
          - release
        default: branch
      ref:
        description: nuxt ref to use
        required: true
        type: string
        default: 4.x
      nitro:
        description: the version of nitro to use
        type: choice
        options:
          - v3 nightly
          - v2 nightly
          - v2 latest
        default: v2 latest
      repo:
        description: nuxt repository to use
        required: true
        type: string
        default: nuxt/nuxt
  repository_dispatch:
    types: [ecosystem-ci]

permissions: {}

jobs:
  test-ecosystem:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    permissions:
      contents: read # to clone the repo
    strategy:
      matrix:
        suite:
          - starter
          - content
          - ui
          - image
          - pinia
          - examples
          - example-layers-monorepo
          - bridge
          - nuxt-com
          - vite-pwa
          - docus
          - og-image
          - histoire
          - elk
          - devtools
          - fonts
          - scripts
          - icon
          - cli
          - test-utils
          - module-builder
          - sanity-module
          - tailwindcss
          - sitemap
          - i18n-module
          # - werewolves-assistant
          - antoine-zanardi-portfolio
          - storybook
          - npmx
      fail-fast: false
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
        with:
          persist-credentials: false
      - run: corepack enable
      - uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6.0.0
        with:
          node-version: lts/*
      - uses: oven-sh/setup-bun@3d267786b128fe76c2f16a390aa2448b815359f3 # v2
        with:
          bun-version: latest
      - uses: denoland/setup-deno@22d081ff2d3a40755e97629de92e3bcbfa7cf2ed # v2
        with:
          deno-version: v2.7.4
      - run: pnpm i --frozen-lockfile
      - if: ${{ !(matrix.suite == 'bridge' && (inputs.ref || github.event.client_payload.ref || '4.x') == '4.x') }}
        run: >-
          pnpm test
          "--$REF_TYPE" "$REF"
          --repo "$REPO"
          "${{ matrix.suite }}"
        id: ecosystem-ci-run
        env:
          REF_TYPE: ${{ inputs.refType || github.event.client_payload.refType || 'branch' }}
          REF: ${{ inputs.ref || github.event.client_payload.ref || '4.x' }}
          REPO: ${{ inputs.repo || github.event.client_payload.repo || 'nuxt/nuxt' }}
          NUXT_UI_PRO_TOKEN: ${{ secrets.NUXT_UI_PRO_TOKEN }}
          NUXT_UI_PRO_LICENSE: ${{ secrets.NUXT_UI_PRO_TOKEN }}
          NITRO_VERSION: ${{ inputs.nitro || 'v2 latest' }}

      - if: always() && !(matrix.suite == 'bridge' && (inputs.ref || github.event.client_payload.ref || '4.x') == '4.x')
        run: node --experimental-strip-types --disable-warning=ExperimentalWarning discord-webhook.ts
        env:
          WORKFLOW_NAME: ci
          REF_TYPE: ${{ inputs.refType || github.event.client_payload.refType || 'branch' }}
          REF: ${{ inputs.ref || github.event.client_payload.ref || '4.x' }}
          REPO: ${{ inputs.repo || github.event.client_payload.repo || 'nuxt/nuxt' }}
          SUITE: ${{ matrix.suite }}
          STATUS: ${{ job.status }}
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
